services:
    db:
        image: mysql:latest
        container_name: vparrot_mysql
        restart: always
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: admin
            MYSQL_USER: admin
        healthcheck:
            test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1'"]
            interval: 10s
            retries: 5
            start_period: 120s
            timeout: 10s
        volumes:
            - mysql_vparrot_data:/var/lib/mysql:rw
        networks:
            - vparrot
    # mailhog: # for dev only
    #     image: mailhog/mailhog
    #     container_name: hr-mailhog
    #     ports:
    #         - "1025:1025"
    #         - "8025:8025"
    #     environment:
    #         MH_STORAGE: memory
    #     networks:
    #         - vparrot
    # rabbit-mq:
    #     # image: rabbitmq:latest # for prod env
    #     image: rabbitmq:3-management # for dev env
    #     container_name: rabbit-mq
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
    #     networks:
    #         - vparrot
    php:
        image: vparrot
        container_name: vparrot_php8.3
        restart: always
        # labels:
        #     - traefik.enable=true
        #     - traefik.http.routers.vparrot-php.rule=Host(`vparrot.ju2breizh.fr`)
        ports:
            - "9020:80"
        networks:
            # - webgateway
            - vparrot
        depends_on:
            db:
                condition: service_healthy
                restart: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
volumes:
    mysql_vparrot_data:
        driver: local

networks:
    vparrot:
        driver: bridge
    # webgateway:
    #     external: true
