use vparrot;


ALTER TABLE users
    CHANGE COLUMN username firstName VARCHAR(150) NOT NULL,
    ADD COLUMN lastName VARCHAR(150) NOT NULL,
    ADD COLUMN email VARCHAR(250) NOT NULL UNIQUE,
    DROP COLUMN password,
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN role VARCHAR(10),
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;
ALTER TABLE users
    MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE authenticates 
    DROP COLUMN email,
    ADD COLUMN password CHAR(64) NOT NULL,
    DROP FOREIGN KEY authenticates_ibfk_1,
    CHANGE COLUMN user_id user INT NOT NULL,
    ADD CONSTRAINT authenticates_users FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE brands 
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE models 
    DROP FOREIGN KEY models_ibfk_1,
    CHANGE COLUMN brand_id brand INT NOT NULL,
    ADD CONSTRAINT models_brands FOREIGN KEY (brand) REFERENCES brands(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE energies 
    CHANGE COLUMN type name VARCHAR(20) NOT NULL,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE cars 
    DROP FOREIGN KEY cars_ibfk_1,
    CHANGE COLUMN model_id model INT NOT NULL,
    ADD CONSTRAINT cars_models FOREIGN KEY (model) REFERENCES models(id) ON UPDATE CASCADE ON DROP CASCADE,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE companies 
    CHANGE COLUMN zip_code zipCode VARCHAR(10) NOT NULL,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE openings 
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHANGE COLUMN open_time openTime TIME NOT NULL,
    CHANGE COLUMN close_time closureTime TIME NOT NULL,
    CHANGE COLUMN day_of_week day VARCHAR(20) NOT NULL,
    DROP FOREIGN KEY openings_ibfk_1,
    CHANGE COLUMN company_id company INT NOT NULL,
    ADD CONSTRAINT openings_companies FOREIGN KEY (company) REFERENCES companies(id) ON UPDATE CASCADE
;

ALTER TABLE services 
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE comments
    DROP FOREIGN KEY comments_ibfk_1,
    CHANGE COLUMN user_id author INT NOT NULL,
    ADD CONSTRAINT FK_comments_users FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CHANGE COLUMN is_approved isApproved TINYINT NOT NULL DEFAULT 0,
    CHANGE COLUMN created_at createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN updated_at updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE messages 
    DROP FOREIGN KEY messages_ibfk_1,     
    DROP FOREIGN KEY messages_ibfk_2,     
    CHANGE COLUMN is_read status VARCHAR(20) NOT NULL,
    ADD CONSTRAINT FK_messages_users FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT FK_messages_cars FOREIGN KEY (car) REFERENCES cars(id) ON DELETE CASCADE ON UPDATE CASCADE
;

ALTER TABLE messages     
    CHANGE COLUMN is_read status VARCHAR(20) NOT NULL
;
